[base]
dimension = 6 #J1, J2, J3, Jm, D1, D3
output_dir = "output"

[algorithm]
name = "mapper"
seed = 12345

[algorithm.param]
#J1,J2,J3,Jm,D1,D3
max_list = [1.336962  , 2.84371817, 0.59735462, 0.39814728, 0.2673924, 0.1203266] #meV
min_list = [1.336962  , 2.84371817, 0.59735462, 0.39814728, 0.2673924, 0.1203266] #meV
num_list = [1, 1, 1, 1, 1, 1]

[solver]
name = "azurite"
path_to_reference = "../exp_J.csv"
path_to_dmrg_library = "/home/k-yoshimi/git/azurite/itensor/dmrg/dmrg.so"
size = 60
eps_cut = 1e-12
sweep_dim = [10, 40, 100, 200, 400]
[runner]
[runner.log]
interval = 100
