[base]
dimension = 4 #J1, J2, J3, Jm
output_dir = "output"

[algorithm]
name = "mapper"
seed = 12345

[algorithm.param]
max_list = [1.336962  , 2.84371817, 0.59735462, 0.39814728] #meV
min_list = [1.336962  , 2.84371817, 0.59735462, 0.39814728] #meV
num_list = [1, 1, 1, 1]

[solver]
name = "azurite"
path_to_reference = "../exp_J.csv"
path_to_dmrg_library = "/home/k-yoshimi/git/azurite/itensor/dmrg/dmrg.so"
size = 60
[runner]
[runner.log]
interval = 100
