[base]
dimension = 6 #J1, J2, J3, Jm, D1, D3
output_dir = "output"

[algorithm]
name = "mapper"
seed = 12345

[algorithm.param]
mesh_path = "target_J.txt"

[solver]
name = "azurite"
path_to_reference = "../exp_J.csv"
path_to_dmrg_library = "/home/k0136/k013603/git/azurite/itensor/dmrg/dmrg.so"
size = 60
eps_cut = 1e-12
sweep_dim = [10, 40, 100, 200, 400]
[runner]
[runner.log]
interval = 100
