[base]
dimension = 4 #J1, J2, J3, Jm
output_dir = "output"

[algorithm]
name = "bayes"
seed = 12345

[algorithm.param]
max_list = [20.0, 10.0, 1.0, 1.0]
min_list = [10.0, 0.0, 0.0, 0.0]
num_list = [21, 21, 21, 21]
# [15.51, 2.127, 0.4468, 0.2978]

[algorithm.bayes]
random_max_num_probes = 10
bayes_max_num_probes = 500

[solver]
name = "azurite"
path_to_reference = "../exp_J.csv"
path_to_dmrg_library = "dmrg.so"
size = 4
